apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: markdowns.this.is.group.com
spec:
  group: this.is.group.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                content:
                  type: string
      additionalPrinterColumns:
      - name: content
        type: string
        description: Content of markdown
        jsonPath: .spec.content
  scope: Namespaced
  names:
    plural: markdowns
    singular: markdowns
    kind: Markdown
    shortNames:
    - md